// The demo site from App v2 (Maple Grove School). The seed writes it and the simulator plays its
// gateway, so both need the same ids. The ids are fixed ObjectId strings; the MQTT gateway
// certificate for DEMO_SITE_ID is generated by infra/mosquitto/gen-certs.sh.
import type { DeviceType } from './signs';

export const DEMO_SITE_ID = '650000000000000000000001';

export const DEMO_SITE = {
  id: DEMO_SITE_ID,
  name: 'Maple Grove School',
  address: '1200 Maple Grove Rd, Toronto ON',
  tz: 'America/Toronto',
  lat: 43.65,
  lon: -79.38,
  currency: 'CAD',
  billDay: 1,
  demandCapKw: 120,
  gatewayId: 'gw-maple-01',
} as const;

export interface DemoDevice {
  id: string;
  key: string; // short name used in fixtures and the simulator
  type: DeviceType;
  name: string;
  profileId: string;
  address: string;
  role: string;
  ratedKw: number | null;
  capacityKwh: number | null;
  kwp?: number; // PV array size
}

const id = (n: number) => `6500000000000000000001${String(n).padStart(2, '0')}`;

export const DEMO_DEVICES: DemoDevice[] = [
  { id: id(1), key: 'invA', type: 'pv', name: 'Inverter A', profileId: 'sunspec-inverter@3', address: '10.0.4.21 · unit 1', role: 'pv', ratedKw: 50, capacityKwh: null, kwp: 48 },
  { id: id(2), key: 'invB', type: 'pv', name: 'Inverter B', profileId: 'sunspec-inverter@3', address: '10.0.4.22 · unit 1', role: 'pv', ratedKw: 40, capacityKwh: null, kwp: 38 },
  { id: id(3), key: 'bat', type: 'battery', name: 'Battery', profileId: 'sunspec-storage-802@2', address: '10.0.4.30 · unit 1', role: 'battery', ratedKw: 60, capacityKwh: 200 },
  { id: id(4), key: 'meter', type: 'meter', name: 'Grid meter', profileId: 'ct-meter-3ph@2', address: 'RS-485 · id 3', role: 'site-meter', ratedKw: null, capacityKwh: null },
  { id: id(5), key: 'ev1', type: 'ev', name: 'EV charger 1', profileId: 'ocpp16-generic@1', address: 'ws://gw.local/ocpp/ev1', role: 'ev', ratedKw: 22, capacityKwh: null },
  { id: id(6), key: 'ev2', type: 'ev', name: 'EV charger 2', profileId: 'ocpp16-generic@1', address: 'ws://gw.local/ocpp/ev2', role: 'ev', ratedKw: 22, capacityKwh: null },
  { id: id(7), key: 'ev3', type: 'ev', name: 'EV charger 3', profileId: 'ocpp16-generic@1', address: 'ws://gw.local/ocpp/ev3', role: 'ev', ratedKw: 22, capacityKwh: null },
  { id: id(8), key: 'ev4', type: 'ev', name: 'EV charger 4', profileId: 'ocpp16-generic@1', address: 'ws://gw.local/ocpp/ev4', role: 'ev', ratedKw: 22, capacityKwh: null },
  { id: id(9), key: 'hp', type: 'heatpump', name: 'Heat pump', profileId: 'sg-ready-heatpump@1', address: 'relay 1–2 · unit 5', role: 'heatpump', ratedKw: 40, capacityKwh: null },
  { id: id(10), key: 'gw', type: 'gateway', name: 'Gateway', profileId: 'gateway@1', address: 'gw-maple-01', role: 'gateway', ratedKw: null, capacityKwh: null },
];

/** Demo sign-ins (password Demo1234!). The seed gives each a membership of the demo site. */
export const DEMO_USERS = [
  { email: 'demo@ecomanage.io', name: 'Priya Shah', role: 'owner', until: null },
  { email: 'manager@ecomanage.io', name: 'Jamie Reyes', role: 'manager', until: null },
  { email: 'installer@ecomanage.io', name: 'Northside Solar', role: 'installer', until: '2026-12-31' },
] as const;
